// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2025-2026 Caleb Kemere, Reet Sinha, Allen Mikhailov, Rice University

// lfp_coef_pkg.sv
//
// GENERATED by programmable_logic/sim/design_lfp_filters.py -- do not hand-edit.
// Re-run that script to change the filters; it also reports the passband ripple,
// the end-to-end alias rejection and the latency each design actually achieves.
//
// Power-on defaults for the LFP decimation chain, Q1.17 signed. These are
// what the board filters with straight out of reset; the host can overwrite
// either stage at runtime without a rebuild.
//
//   stage 1: 11-tap halfband,          30 kHz -> 15 kHz
//   stage 2: 120-tap linear phase,     15 kHz -> 3 kHz, passband to 1200 Hz
//
// Stage 1 is a halfband, so 4 of its 11 taps are structurally zero and its
// centre tap is exactly 0.5. The engine still MACs all 11: the zeros cost idle
// cycles the budget can spare, and skipping them would silently mis-compute any
// non-halfband coefficients a user uploads.
//
// A minimum-phase stage 2 with the same magnitude response but ~4.6x less
// latency is in lfp_poly120_min_coefs.hex -- upload it when latency matters
// more than constant group delay.

package lfp_coef_pkg;

    localparam int LFP_COEF_W    = 18;
    localparam int LFP_COEF_FRAC = 17;
    localparam int LFP_HB_TAPS   = 11;
    localparam int LFP_POLY_TAPS = 120;

    localparam logic [17:0] LFP_HB_DEFAULT_COEF [0:10] = '{
        18'h003be, 18'h00000, 18'h3e4f7, 18'h00000, 18'h0974a, 18'h10000,
        18'h0974a, 18'h00000, 18'h3e4f7, 18'h00000, 18'h003be
    };

    localparam logic [17:0] LFP_POLY_DEFAULT_COEF [0:119] = '{
        18'h3fffd, 18'h3fffe, 18'h00000, 18'h00005, 18'h0000d, 18'h00014,
        18'h00018, 18'h00013, 18'h00003, 18'h3ffec, 18'h3ffd4, 18'h3ffc6,
        18'h3ffcd, 18'h3ffed, 18'h00021, 18'h00058, 18'h0007a, 18'h00073,
        18'h00037, 18'h3ffd3, 18'h3ff66, 18'h3ff1c, 18'h3ff1f, 18'h3ff82,
        18'h00032, 18'h000f9, 18'h00186, 18'h00192, 18'h000fa, 18'h3ffd8,
        18'h3fe87, 18'h3fd8b, 18'h3fd5d, 18'h3fe3b, 18'h00002, 18'h00223,
        18'h003d0, 18'h00442, 18'h0030c, 18'h00059, 18'h3fcfa, 18'h3fa2e,
        18'h3f936, 18'h3fad7, 18'h3feeb, 18'h0044c, 18'h0090e, 18'h00b1d,
        18'h00907, 18'h002a6, 18'h3f97f, 18'h3f08a, 18'h3eb7a, 18'h3eda4,
        18'h3f8e1, 18'h00cbd, 18'h02650, 18'h040c8, 18'h05696, 18'h062e5,
        18'h062e5, 18'h05696, 18'h040c8, 18'h02650, 18'h00cbd, 18'h3f8e1,
        18'h3eda4, 18'h3eb7a, 18'h3f08a, 18'h3f97f, 18'h002a6, 18'h00907,
        18'h00b1d, 18'h0090e, 18'h0044c, 18'h3feeb, 18'h3fad7, 18'h3f936,
        18'h3fa2e, 18'h3fcfa, 18'h00059, 18'h0030c, 18'h00442, 18'h003d0,
        18'h00223, 18'h00002, 18'h3fe3b, 18'h3fd5d, 18'h3fd8b, 18'h3fe87,
        18'h3ffd8, 18'h000fa, 18'h00192, 18'h00186, 18'h000f9, 18'h00032,
        18'h3ff82, 18'h3ff1f, 18'h3ff1c, 18'h3ff66, 18'h3ffd3, 18'h00037,
        18'h00073, 18'h0007a, 18'h00058, 18'h00021, 18'h3ffed, 18'h3ffcd,
        18'h3ffc6, 18'h3ffd4, 18'h3ffec, 18'h00003, 18'h00013, 18'h00018,
        18'h00014, 18'h0000d, 18'h00005, 18'h00000, 18'h3fffe, 18'h3fffd
    };

endpackage
