# Constraints for 8 digital inputs

set_property PACKAGE_PIN P16 [get_ports {digital_in_0[0]}]
set_property PACKAGE_PIN P15 [get_ports {digital_in_0[1]}]
set_property PACKAGE_PIN W19 [get_ports {digital_in_0[2]}]
set_property PACKAGE_PIN W18 [get_ports {digital_in_0[3]}]
set_property PACKAGE_PIN R18 [get_ports {digital_in_0[4]}]
set_property PACKAGE_PIN T17 [get_ports {digital_in_0[5]}]
set_property PACKAGE_PIN W16 [get_ports {digital_in_0[6]}]
set_property PACKAGE_PIN V16 [get_ports {digital_in_0[7]}]

set_property DIRECTION IN [get_ports {digital_in_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digital_in_0[7]}]
set_property PULLTYPE PULLDOWN [get_ports {digital_in_0[7]}]
set_property DIRECTION IN [get_ports {digital_in_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digital_in_0[6]}]
set_property PULLTYPE PULLDOWN [get_ports {digital_in_0[6]}]
set_property DIRECTION IN [get_ports {digital_in_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digital_in_0[5]}]
set_property PULLTYPE PULLDOWN [get_ports {digital_in_0[5]}]
set_property DIRECTION IN [get_ports {digital_in_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digital_in_0[4]}]
set_property PULLTYPE PULLDOWN [get_ports {digital_in_0[4]}]
set_property DIRECTION IN [get_ports {digital_in_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digital_in_0[3]}]
set_property PULLTYPE PULLDOWN [get_ports {digital_in_0[3]}]
set_property DIRECTION IN [get_ports {digital_in_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digital_in_0[2]}]
set_property PULLTYPE PULLDOWN [get_ports {digital_in_0[2]}]
set_property DIRECTION IN [get_ports {digital_in_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digital_in_0[1]}]
set_property PULLTYPE PULLDOWN [get_ports {digital_in_0[1]}]
set_property DIRECTION IN [get_ports {digital_in_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digital_in_0[0]}]
set_property PULLTYPE PULLDOWN [get_ports {digital_in_0[0]}]
