# Intan SPI LVDS Interface Constraints
# This file provides pin assignments and I/O standards for the LVDS SPI interface
# Modify the PACKAGE_PIN assignments to match your specific FPGA and PCB layout

#==============================================================================
# LVDS SPI Clock - Differential Pair
#==============================================================================
set_property IOSTANDARD LVDS_25 [get_ports spi_lvds_0_lvds_0_sclk_p]
set_property IOSTANDARD LVDS_25 [get_ports spi_lvds_0_lvds_0_sclk_n]
set_property PACKAGE_PIN E17 [get_ports spi_lvds_0_lvds_0_sclk_p]
set_property PACKAGE_PIN D18 [get_ports spi_lvds_0_lvds_0_sclk_n]

# Clock output timing constraints
# SPI controller runs on 84MHz clock, so all outputs are relative to this clock
# 24MHz SPI clock is generated by dividing the 84MHz controller clock
set_output_delay -clock [get_clocks clk_out1_design_1_clk_wiz_0_84M_175M_0] -max 2.0 [get_ports {spi_lvds_0_lvds_0_sclk_p spi_lvds_0_lvds_0_sclk_n}]
set_output_delay -clock [get_clocks clk_out1_design_1_clk_wiz_0_84M_175M_0] -min -2.0 [get_ports {spi_lvds_0_lvds_0_sclk_p spi_lvds_0_lvds_0_sclk_n}]
set_output_delay -clock [get_clocks clk_out1_design_1_clk_wiz_0_84M_175M_0] -max 2.0 [get_ports {spi_lvds_0_csn_p spi_lvds_0_csn_n}]
set_output_delay -clock [get_clocks clk_out1_design_1_clk_wiz_0_84M_175M_0] -min -2.0 [get_ports {spi_lvds_0_csn_p spi_lvds_0_csn_n}]
set_output_delay -clock [get_clocks clk_out1_design_1_clk_wiz_0_84M_175M_0] -max 2.0 [get_ports {spi_lvds_0_copi_p spi_lvds_0_copi_n}]
set_output_delay -clock [get_clocks clk_out1_design_1_clk_wiz_0_84M_175M_0] -min -2.0 [get_ports {spi_lvds_0_copi_p spi_lvds_0_copi_n}]

# Optional: Define the 24MHz SPI clock as a generated clock for more accurate analysis
# This tells Vivado that spi_lvds_0_sclk is derived from the 84MHz controller clock with ~3.5x division
# create_generated_clock -name spi_lvds_0_sclk_24mhz -source [get_pins your_spi_lvds_0_controller_instance/clk] -divide_by 3.5 [get_ports spi_lvds_0_sclk_p]

#==============================================================================
# LVDS SPI Chip Select (Active Low) - Differential Pair
#==============================================================================
set_property IOSTANDARD LVDS_25 [get_ports spi_lvds_0_csn_p]
set_property IOSTANDARD LVDS_25 [get_ports spi_lvds_0_csn_n]
set_property PACKAGE_PIN D19 [get_ports spi_lvds_0_csn_p]
set_property PACKAGE_PIN D20 [get_ports spi_lvds_0_csn_n]

#==============================================================================
# LVDS SPI Controller Out Peripheral In (COPI/MOSI) - Differential Pair
#==============================================================================
set_property IOSTANDARD LVDS_25 [get_ports spi_lvds_0_copi_p]
set_property IOSTANDARD LVDS_25 [get_ports spi_lvds_0_copi_n]
set_property PACKAGE_PIN F16 [get_ports spi_lvds_0_copi_p]
set_property PACKAGE_PIN F17 [get_ports spi_lvds_0_copi_n]

#==============================================================================
# LVDS SPI Controller In Peripheral Out Channel 0 (CIPO0/MISO0) - Differential Pair
#==============================================================================
set_property IOSTANDARD LVDS_25 [get_ports spi_lvds_0_cipo0_p]
set_property IOSTANDARD LVDS_25 [get_ports spi_lvds_0_cipo0_n]
set_property PACKAGE_PIN E18 [get_ports spi_lvds_0_cipo0_p]
set_property PACKAGE_PIN E19 [get_ports spi_lvds_0_cipo0_n]

# Input timing constraints for CIPO0
# Using your actual 84MHz sampling clock from Clocking Wizard
set_input_delay -clock [get_clocks clk_out1_design_1_clk_wiz_0_84M_175M_0] -max 3.0 [get_ports {spi_lvds_0_cipo0_p spi_lvds_0_cipo0_n}]
set_input_delay -clock [get_clocks clk_out1_design_1_clk_wiz_0_84M_175M_0] -min 0.5 [get_ports {spi_lvds_0_cipo0_p spi_lvds_0_cipo0_n}]

#==============================================================================
# LVDS SPI Controller In Peripheral Out Channel 1 (CIPO1/MISO1) - Differential Pair
#==============================================================================
set_property IOSTANDARD LVDS_25 [get_ports spi_lvds_0_cipo1_p]
set_property IOSTANDARD LVDS_25 [get_ports spi_lvds_0_cipo1_n]
set_property PACKAGE_PIN M19 [get_ports spi_lvds_0_cipo1_p]
set_property PACKAGE_PIN M20 [get_ports spi_lvds_0_cipo1_n]

# Input timing constraints for CIPO1
# Using your actual 84MHz sampling clock from Clocking Wizard
set_input_delay -clock [get_clocks clk_out1_design_1_clk_wiz_0_84M_175M_0] -max 3.0 [get_ports {spi_lvds_0_cipo1_p spi_lvds_0_cipo1_n}]
set_input_delay -clock [get_clocks clk_out1_design_1_clk_wiz_0_84M_175M_0] -min 0.5 [get_ports {spi_lvds_0_cipo1_p spi_lvds_0_cipo1_n}]

#==============================================================================
# Additional LVDS-specific properties
#==============================================================================

# Set differential termination for input pairs (improves signal integrity)
set_property DIFF_TERM TRUE [get_ports spi_lvds_0_cipo0_p]
set_property DIFF_TERM TRUE [get_ports spi_lvds_0_cipo1_p]

# Set slew rate for output pairs (FAST for high-speed operation)
set_property SLEW FAST [get_ports spi_lvds_0_sclk_p]
set_property SLEW FAST [get_ports spi_lvds_0_csn_p]
set_property SLEW FAST [get_ports spi_lvds_0_copi_p]

# Set drive strength for outputs (12mA is typical for LVDS_25)
set_property DRIVE 12 [get_ports spi_lvds_0_sclk_p]
set_property DRIVE 12 [get_ports spi_lvds_0_csn_p]
set_property DRIVE 12 [get_ports spi_lvds_0_copi_p]

#==============================================================================
# Physical placement constraints (optional - for better signal integrity)
#==============================================================================

# Keep differential pairs close together
set_property LOC DIFF_PAIR_0 [get_ports {spi_lvds_0_sclk_p spi_lvds_0_sclk_n}]
set_property LOC DIFF_PAIR_1 [get_ports {spi_lvds_0_csn_p spi_lvds_0_csn_n}]
set_property LOC DIFF_PAIR_2 [get_ports {spi_lvds_0_copi_p spi_lvds_0_copi_n}]
set_property LOC DIFF_PAIR_3 [get_ports {spi_lvds_0_cipo0_p spi_lvds_0_lvds_0_cipo0_n}]
set_property LOC DIFF_PAIR_4 [get_ports {spi_lvds_0_lvds_0_cipo1_p spi_lvds_0_lvds_0_cipo1_n}]

#==============================================================================
# Timing exceptions (if needed)
#==============================================================================

# If CSN is asynchronous to SCLK, add false path
# set_false_path -from [get_ports spi_lvds_0_lvds_0_csn_p] -to [all_registers]

# Clock domain crossing constraints (if SPI clock is in different domain)
# set_clock_groups -asynchronous -group [get_clocks spi_lvds_0_lvds_0_sclk] -group [get_clocks your_system_clock]

#==============================================================================
# Board-specific notes and pin assignment examples
#==============================================================================

# Example pin assignments for common Xilinx development boards:

# For Zynq UltraScale+ MPSoC (ZCU102/ZCU104):
# Bank 67 LVDS pins (HR I/O, supports LVDS_25)
# set_property PACKAGE_PIN G26 [get_ports spi_lvds_0_lvds_0_sclk_p]    ; # Bank 67
# set_property PACKAGE_PIN F26 [get_ports spi_lvds_0_lvds_0_sclk_n]    ; # Bank 67
# set_property PACKAGE_PIN H26 [get_ports spi_lvds_0_lvds_0_csn_p]     ; # Bank 67
# set_property PACKAGE_PIN H27 [get_ports spi_lvds_0_lvds_0_csn_n]     ; # Bank 67
# set_property PACKAGE_PIN J25 [get_ports spi_lvds_0_lvds_0_copi_p]    ; # Bank 67
# set_property PACKAGE_PIN J26 [get_ports spi_lvds_0_lvds_0_copi_n]    ; # Bank 67
# set_property PACKAGE_PIN K25 [get_ports spi_lvds_0_lvds_0_cipo0_p]   ; # Bank 67
# set_property PACKAGE_PIN K26 [get_ports spi_lvds_0_lvds_0_cipo0_n]   ; # Bank 67
# set_property PACKAGE_PIN L25 [get_ports spi_lvds_0_lvds_0_cipo1_p]   ; # Bank 67
# set_property PACKAGE_PIN L26 [get_ports spi_lvds_0_lvds_0_cipo1_n]   ; # Bank 67

# For Kintex-7 (KC705):
# Bank 16 LVDS pins
# set_property PACKAGE_PIN AC19 [get_ports spi_lvds_0_lvds_0_sclk_p]   ; # Bank 16
# set_property PACKAGE_PIN AD19 [get_ports spi_lvds_0_lvds_0_sclk_n]   ; # Bank 16
# set_property PACKAGE_PIN AE18 [get_ports spi_lvds_0_lvds_0_csn_p]    ; # Bank 16
# set_property PACKAGE_PIN AF18 [get_ports spi_lvds_0_lvds_0_csn_n]    ; # Bank 16
# set_property PACKAGE_PIN AC18 [get_ports spi_lvds_0_lvds_0_copi_p]   ; # Bank 16
# set_property PACKAGE_PIN AD18 [get_ports spi_lvds_0_lvds_0_copi_n]   ; # Bank 16
# set_property PACKAGE_PIN AB17 [get_ports spi_lvds_0_lvds_0_cipo0_p]  ; # Bank 16
# set_property PACKAGE_PIN AC17 [get_ports spi_lvds_0_lvds_0_cipo0_n]  ; # Bank 16
# set_property PACKAGE_PIN AA17 [get_ports spi_lvds_0_lvds_0_cipo1_p]  ; # Bank 16
# set_property PACKAGE_PIN AB16 [get_ports spi_lvds_0_lvds_0_cipo1_n]  ; # Bank 16

#==============================================================================
# Important Notes:
#==============================================================================
# 1. Verify that your chosen pins support LVDS_25 I/O standard
# 2. Check your FPGA's datasheet for LVDS-capable banks
# 3. Ensure differential pairs are properly matched on your PCB
# 4. Add appropriate series termination resistors (typically 100Ω differential)
# 5. Keep differential trace lengths matched (within ±0.1mm)
# 6. Route differential pairs away from switching signals to minimize crosstalk
# 7. Use ground planes and proper layer stackup for signal integrity
# 8. Verify VCCO voltage for the selected bank matches LVDS_25 requirements (2.5V)

#==============================================================================
# Validation commands (uncomment to check constraints)
#==============================================================================
# report_property [get_ports spi_lvds_0_lvds_0_*]
# check_timing -verbose
# report_timing_summary
# report_drc
