# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2025-2026 Caleb Kemere, Reet Sinha, Allen Mikhailov, Rice University

# Intan SPI LVDS Interface Constraints
# This file provides pin assignments and I/O standards for the LVDS SPI interface
# Modify the PACKAGE_PIN assignments to match your specific FPGA and PCB layout

#==============================================================================
# LVDS SPI Clock - Differential Pair
#==============================================================================
set_property IOSTANDARD LVDS_25 [get_ports spi_lvds_0_sclk_p]
set_property IOSTANDARD LVDS_25 [get_ports spi_lvds_0_sclk_n]
set_property PACKAGE_PIN E17 [get_ports spi_lvds_0_sclk_p]
set_property PACKAGE_PIN D18 [get_ports spi_lvds_0_sclk_n]

# Clock output timing constraints
# SPI controller runs on 84MHz clock, so all outputs are relative to this clock
# 24MHz SPI clock is generated by dividing the 84MHz controller clock
set_output_delay -clock [get_clocks clk_out1_design_1_clk_wiz_0_84M_175M_0] -max 2.0 [get_ports {spi_lvds_0_lvds_0_sclk_p spi_lvds_0_lvds_0_sclk_n}]
set_output_delay -clock [get_clocks clk_out1_design_1_clk_wiz_0_84M_175M_0] -min -2.0 [get_ports {spi_lvds_0_lvds_0_sclk_p spi_lvds_0_lvds_0_sclk_n}]
set_output_delay -clock [get_clocks clk_out1_design_1_clk_wiz_0_84M_175M_0] -max 2.0 [get_ports {spi_lvds_0_csn_p spi_lvds_0_csn_n}]
set_output_delay -clock [get_clocks clk_out1_design_1_clk_wiz_0_84M_175M_0] -min -2.0 [get_ports {spi_lvds_0_csn_p spi_lvds_0_csn_n}]
set_output_delay -clock [get_clocks clk_out1_design_1_clk_wiz_0_84M_175M_0] -max 2.0 [get_ports {spi_lvds_0_copi_p spi_lvds_0_copi_n}]
set_output_delay -clock [get_clocks clk_out1_design_1_clk_wiz_0_84M_175M_0] -min -2.0 [get_ports {spi_lvds_0_copi_p spi_lvds_0_copi_n}]

# Optional: Define the 24MHz SPI clock as a generated clock for more accurate analysis
# This tells Vivado that spi_lvds_0_sclk is derived from the 84MHz controller clock with ~3.5x division
# create_generated_clock -name spi_lvds_0_sclk_24mhz -source [get_pins your_spi_lvds_0_controller_instance/clk] -divide_by 3.5 [get_ports spi_lvds_0_sclk_p]

#==============================================================================
# LVDS SPI Chip Select (Active Low) - Differential Pair
#==============================================================================
set_property IOSTANDARD LVDS_25 [get_ports spi_lvds_0_csn_p]
set_property IOSTANDARD LVDS_25 [get_ports spi_lvds_0_csn_n]
set_property PACKAGE_PIN D19 [get_ports spi_lvds_0_csn_p]
set_property PACKAGE_PIN D20 [get_ports spi_lvds_0_csn_n]

#==============================================================================
# LVDS SPI Controller Out Peripheral In (COPI/MOSI) - Differential Pair
#==============================================================================
set_property IOSTANDARD LVDS_25 [get_ports spi_lvds_0_copi_p]
set_property IOSTANDARD LVDS_25 [get_ports spi_lvds_0_copi_n]
set_property PACKAGE_PIN F16 [get_ports spi_lvds_0_copi_p]
set_property PACKAGE_PIN F17 [get_ports spi_lvds_0_copi_n]

#==============================================================================
# LVDS SPI Controller In Peripheral Out Channel 0 (CIPO0/MISO0) - Differential Pair
#==============================================================================
set_property IOSTANDARD LVDS_25 [get_ports spi_lvds_0_cipo0_p]
set_property IOSTANDARD LVDS_25 [get_ports spi_lvds_0_cipo0_n]
set_property PACKAGE_PIN E18 [get_ports spi_lvds_0_cipo0_p]
set_property PACKAGE_PIN E19 [get_ports spi_lvds_0_cipo0_n]

# Input timing constraints for CIPO0
# Using your actual 84MHz sampling clock from Clocking Wizard
set_input_delay -clock [get_clocks clk_out1_design_1_clk_wiz_0_84M_175M_0] -max 3.0 [get_ports {spi_lvds_0_cipo0_p spi_lvds_0_cipo0_n}]
set_input_delay -clock [get_clocks clk_out1_design_1_clk_wiz_0_84M_175M_0] -min 0.5 [get_ports {spi_lvds_0_cipo0_p spi_lvds_0_cipo0_n}]

#==============================================================================
# LVDS SPI Controller In Peripheral Out Channel 1 (CIPO1/MISO1) - Differential Pair
#==============================================================================
set_property IOSTANDARD LVDS_25 [get_ports spi_lvds_0_cipo1_p]
set_property IOSTANDARD LVDS_25 [get_ports spi_lvds_0_cipo1_n]
set_property PACKAGE_PIN M19 [get_ports spi_lvds_0_cipo1_p]
set_property PACKAGE_PIN M20 [get_ports spi_lvds_0_cipo1_n]

# Input timing constraints for CIPO1
# Using your actual 84MHz sampling clock from Clocking Wizard
set_input_delay -clock [get_clocks clk_out1_design_1_clk_wiz_0_84M_175M_0] -max 3.0 [get_ports {spi_lvds_0_cipo1_p spi_lvds_0_cipo1_n}]
set_input_delay -clock [get_clocks clk_out1_design_1_clk_wiz_0_84M_175M_0] -min 0.5 [get_ports {spi_lvds_0_cipo1_p spi_lvds_0_cipo1_n}]

#==============================================================================
# Additional LVDS-specific properties
#==============================================================================

# Set differential termination for input pairs (improves signal integrity)
set_property DIFF_TERM TRUE [get_ports spi_lvds_0_cipo0_p]
set_property DIFF_TERM TRUE [get_ports spi_lvds_0_cipo1_p]

# Set slew rate for output pairs (FAST for high-speed operation)
set_property SLEW FAST [get_ports spi_lvds_0_sclk_p]
set_property SLEW FAST [get_ports spi_lvds_0_csn_p]
set_property SLEW FAST [get_ports spi_lvds_0_copi_p]

# Set drive strength for outputs (12mA is typical for LVDS_25)
set_property DRIVE 12 [get_ports spi_lvds_0_sclk_p]
set_property DRIVE 12 [get_ports spi_lvds_0_csn_p]
set_property DRIVE 12 [get_ports spi_lvds_0_copi_p]

#==============================================================================
# SECOND CABLE PORT (port B) -- spi_lvds_1, bank 35, LVDS_25.
#------------------------------------------------------------------------------
# Shares the broadcast SCLK/CSN/COPI with port A (common command set), with its
# own CIPO return lines. Pins are the carrier-schematic bank-35 pairs:
#   CS   = IO_L15 (F19/F20)   SCLK = IO_L17 (J20/H20)   COPI = IO_L19 (H15/G15)
#   cipo2 (spi_lvds_1_cipo0) = IO_L22 (L14/L15)
#   cipo3 (spi_lvds_1_cipo1) = IO_L24 (K16/J16)
# Resolved schematic IO_L-pair names -> clg400 balls via the device database;
# bank 35 is the same LVDS_25/VCCO-2.5V bank port A uses. (COPI's IO_L19 has no
# XADC qualifier and exists in 3 banks; bank 35 chosen because the whole
# interface lives there -- VERIFY F19/F20/J20/H20/H15/G15/L14/L15/K16/J16
# against the board before first power-on.)
#==============================================================================

set CLK [get_clocks clk_out1_design_1_clk_wiz_0_84M_175M_0]

# --- SCLK (output, IO_L17) ---
set_property IOSTANDARD LVDS_25 [get_ports {spi_lvds_1_sclk_p spi_lvds_1_sclk_n}]
set_property PACKAGE_PIN J20 [get_ports spi_lvds_1_sclk_p]
set_property PACKAGE_PIN H20 [get_ports spi_lvds_1_sclk_n]
set_output_delay -clock $CLK -max  2.0 [get_ports {spi_lvds_1_sclk_p spi_lvds_1_sclk_n}]
set_output_delay -clock $CLK -min -2.0 [get_ports {spi_lvds_1_sclk_p spi_lvds_1_sclk_n}]

# --- CSN (output, IO_L15) ---
set_property IOSTANDARD LVDS_25 [get_ports {spi_lvds_1_csn_p spi_lvds_1_csn_n}]
set_property PACKAGE_PIN F19 [get_ports spi_lvds_1_csn_p]
set_property PACKAGE_PIN F20 [get_ports spi_lvds_1_csn_n]
set_output_delay -clock $CLK -max  2.0 [get_ports {spi_lvds_1_csn_p spi_lvds_1_csn_n}]
set_output_delay -clock $CLK -min -2.0 [get_ports {spi_lvds_1_csn_p spi_lvds_1_csn_n}]

# --- COPI (output, IO_L19) ---
set_property IOSTANDARD LVDS_25 [get_ports {spi_lvds_1_copi_p spi_lvds_1_copi_n}]
set_property PACKAGE_PIN H15 [get_ports spi_lvds_1_copi_p]
set_property PACKAGE_PIN G15 [get_ports spi_lvds_1_copi_n]
set_output_delay -clock $CLK -max  2.0 [get_ports {spi_lvds_1_copi_p spi_lvds_1_copi_n}]
set_output_delay -clock $CLK -min -2.0 [get_ports {spi_lvds_1_copi_p spi_lvds_1_copi_n}]

# --- CIPO0 = cipo2 (input, IO_L22) ---
set_property IOSTANDARD LVDS_25 [get_ports {spi_lvds_1_cipo0_p spi_lvds_1_cipo0_n}]
set_property PACKAGE_PIN L14 [get_ports spi_lvds_1_cipo0_p]
set_property PACKAGE_PIN L15 [get_ports spi_lvds_1_cipo0_n]
set_property DIFF_TERM TRUE  [get_ports spi_lvds_1_cipo0_p]
set_input_delay -clock $CLK -max 3.0 [get_ports {spi_lvds_1_cipo0_p spi_lvds_1_cipo0_n}]
set_input_delay -clock $CLK -min 0.5 [get_ports {spi_lvds_1_cipo0_p spi_lvds_1_cipo0_n}]

# --- CIPO1 = cipo3 (input, IO_L24) ---
set_property IOSTANDARD LVDS_25 [get_ports {spi_lvds_1_cipo1_p spi_lvds_1_cipo1_n}]
set_property PACKAGE_PIN K16 [get_ports spi_lvds_1_cipo1_p]
set_property PACKAGE_PIN J16 [get_ports spi_lvds_1_cipo1_n]
set_property DIFF_TERM TRUE  [get_ports spi_lvds_1_cipo1_p]
set_input_delay -clock $CLK -max 3.0 [get_ports {spi_lvds_1_cipo1_p spi_lvds_1_cipo1_n}]
set_input_delay -clock $CLK -min 0.5 [get_ports {spi_lvds_1_cipo1_p spi_lvds_1_cipo1_n}]

# Slew / drive on the port-B outputs
set_property SLEW FAST [get_ports {spi_lvds_1_sclk_p spi_lvds_1_csn_p spi_lvds_1_copi_p}]
set_property DRIVE 12  [get_ports {spi_lvds_1_sclk_p spi_lvds_1_csn_p spi_lvds_1_copi_p}]

#==============================================================================
# Physical placement constraints (optional - for better signal integrity)
#==============================================================================

# Keep differential pairs close together
set_property LOC DIFF_PAIR_0 [get_ports {spi_lvds_0_sclk_p spi_lvds_0_sclk_n}]
set_property LOC DIFF_PAIR_1 [get_ports {spi_lvds_0_csn_p spi_lvds_0_csn_n}]
set_property LOC DIFF_PAIR_2 [get_ports {spi_lvds_0_copi_p spi_lvds_0_copi_n}]
set_property LOC DIFF_PAIR_3 [get_ports {spi_lvds_0_cipo0_p spi_lvds_0_lvds_0_cipo0_n}]
set_property LOC DIFF_PAIR_4 [get_ports {spi_lvds_0_lvds_0_cipo1_p spi_lvds_0_lvds_0_cipo1_n}]

#==============================================================================
# Timing exceptions (if needed)
#==============================================================================

# If CSN is asynchronous to SCLK, add false path
# set_false_path -from [get_ports spi_lvds_0_lvds_0_csn_p] -to [all_registers]

# Clock domain crossing constraints (if SPI clock is in different domain)
# set_clock_groups -asynchronous -group [get_clocks spi_lvds_0_lvds_0_sclk] -group [get_clocks your_system_clock]


#==============================================================================
# Important Notes:
#==============================================================================
# 1. Verify that your chosen pins support LVDS_25 I/O standard
# 2. Check your FPGA's datasheet for LVDS-capable banks
# 3. Ensure differential pairs are properly matched on your PCB
# 4. Add appropriate series termination resistors (typically 100Ω differential)
# 5. Keep differential trace lengths matched (within ±0.1mm)
# 6. Route differential pairs away from switching signals to minimize crosstalk
# 7. Use ground planes and proper layer stackup for signal integrity
# 8. Verify VCCO voltage for the selected bank matches LVDS_25 requirements (2.5V)

#==============================================================================
# Validation commands (uncomment to check constraints)
#==============================================================================
# report_property [get_ports spi_lvds_0_lvds_0_*]
# check_timing -verbose
# report_timing_summary
# report_drc
