# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2025-2026 Caleb Kemere, Reet Sinha, Allen Mikhailov, Rice University

# zzz_clock_groups.xdc
#
# The 84 MHz (clk_out1) and 175 MHz (clk_out2) clocks are both generated by the same
# clk_wiz MMCM, but logic in the two domains communicates ONLY through clock-domain-
# crossing structures:
#   * axi_lite_registers: control regs (AXI 175 -> PL 84) and status regs (PL 84 ->
#     AXI 175) are passed through 2-flop (ctrl_sync1/ctrl_sync2) synchronizers.
#   * the capture buffer (simple_dual_port_bram): true dual-port BRAM, write port A on
#     84 MHz, read port B on 175 MHz -- the crossing is handled inside the BRAM.
# There are no single-cycle synchronous register-to-register paths between the two
# domains, so they must be declared asynchronous. Without this, every CDC bit is timed
# against the ~0.476 ns 84/175 beat and reported as a (false) setup violation.
#
# (The auto-exported top.xdc even carries the note: "The clocks are asynchronous, user
#  should constrain them appropriately." -- this is that constraint.)
#
# Named zzz_* so it is read after top.xdc, after the clocks are defined.

set_clock_groups -name async_84_175 -asynchronous \
  -group [get_clocks -include_generated_clocks clk_out1_design_1_clk_wiz_0_84M_175M_0] \
  -group [get_clocks -include_generated_clocks clk_out2_design_1_clk_wiz_0_84M_175M_0]
